name: Deploy to Hugging Face Space

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Login to Hugging Face
      - name: Login to Hugging Face
        run: echo "${{ secrets.HUGGINGFACE_TOKEN }}" | huggingface-cli login

      # Step 5: Deploy to Hugging Face Space
      - name: Deploy to Hugging Face Space
        run: |
          git config --global user.email "duaamansur123@gmail.com"
          git config --global user.name "Duaa Mansur"
          git remote add hf https://huggingface.co/spaces/duaa_mansur/task1
          git push hf main --force
