name: Deploy to Hugging Face Space

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository code
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Deploy to Hugging Face Space
      - name: Deploy to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HUGGINGFACE_TOKEN }}
        run: |
          git config --global user.email "duaamansur123@gmail.com"
          git config --global user.name "Duaa Mansur"
          git remote add hf https://huggingface-cli:$HF_TOKEN@huggingface.co/spaces/duaamansur/task1 || echo "Remote already exists"
          git push https://huggingface-cli:$HF_TOKEN@huggingface.co/spaces/duaamansur/task1 main --force

