name: Sync to Hugging Face Hub

on:
  push:
    branches: [main]

  # Allow manual workflow dispatch from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Step 2: Add remote for Hugging Face Space
      - name: Add remote
        env:
          HF_TOKEN: ${{ secrets.HUGGINGFACE_TOKEN }}
        run: |
          git remote add space https://huggingface-cli:$HF_TOKEN@huggingface.co/spaces/duaamansur/task1 || echo "Remote already exists"

      # Step 3: Push to Hugging Face Space
      - name: Push to Hub
        env:
          HF_TOKEN: ${{ secrets.HUGGINGFACE_TOKEN }}
        run: |
          git push --force https://huggingface-cli:$HF_TOKEN@huggingface.co/spaces/duaamansur/task1 main

